### ISSUE TITLE
Unsafe type assertion in PubSub cause panic: interface {} is []interface {}, not string

### ISSUE THREAD

**Issue by x1unix** [redis/go-redis#1933]
Hello, our project recently migrated to a new version of `go-redis` - v8 and I faced a panic from the library.

```
panic: interface conversion: interface {} is []interface {}, not string

goroutine 117 [running]:
github.com/go-redis/redis/v8.(*PubSub).newMessage(0xc00022a000, 0xaf1560, 0xc01fc0f9b0, 0xc00079c370, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/pubsub.go:313 +0xbd3
github.com/go-redis/redis/v8.(*PubSub).ReceiveTimeout(0xc00022a000, 0xcbd508, 0xc0000240b8, 0x0, 0xb1e580, 0xc01181da90, 0x0, 0x0)
        /root/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/pubsub.go:384 +0x198
github.com/go-redis/redis/v8.(*PubSub).Receive(...)
        /root/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/pubsub.go:391
github.com/go-redis/redis/v8.(*PubSub).ReceiveMessage(0xc00022a000, 0xcbd508, 0xc0000240b8, 0x0, 0x0, 0xc00022a000)
        /root/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/pubsub.go:399 +0x4d
```

Looks like issue is caused by non-safe interface convertion in `go-redis/redis/pubsub.go:306`

```go
func (c *PubSub) newMessage(reply interface{}) (interface{}, error) {
	switch reply := reply.(type) {
	case string:
		return &Pong{
			Payload: reply,
		}, nil
	case []interface{}:
		switch kind := reply[0].(string); kind {
		case "subscribe", "unsubscribe", "psubscribe", "punsubscribe":
			// Can be nil in case of "unsubscribe".
			channel, _ := reply[1].(string)
			return &Subscription{
				Kind:    kind,
				Channel: channel,
				Count:   int(reply[2].(int64)),
			}, nil
		case "message":
			switch payload := reply[2].(type) {
			case string:
				return &Message{
					Channel: reply[1].(string),
					Payload: payload,
				}, nil
			case []interface{}:

...
```

Also I found other unsafe type assertions in other places:

* `command.go:1424` - `readXMessage`

## Expected Behavior

No panics and safe type-assertion.

## Current Behavior

Panic from inner `PubSub.newMessage` method.

## Possible Solution

Add safe type assertion, like:

```diff
case "message":
switch payload := reply[2].(type) {
	case string:
+		chanName, ok := reply[1].(string)
+		// TODO: handle type assertion failure
+
		return &Message{
-			Channel: reply[1].(string),
+			Channel: chanName,
			Payload: payload,
		}, nil
	case []interface{}:
		ss := make([]string, len(payload))
		for i, s := range payload {
+			strVal, _ := s.(string)
+			ss[i] = strVal
-			ss[i] = s.(string)
		}		
		return &Message{
+			// TODO: add safe type assertion
			Channel:      reply[1].(string),
			PayloadSlice: ss,
		}, nil
	default:
		return nil, fmt.Errorf("redis: unsupported pubsub message payload: %T", payload)
	}
```
## Steps to Reproduce

1.
2.
3.
4.

**Comment by x1unix** [comment]
@monkey92t 

Redis: 3.0.6
Go-Redis: v8.11.4

We're using `PubSub.ReceiveMessage`. Please take a look at stack trace in issue description.

```go
pubSub := client.Subscribe(ctx, channel)
msg, err := pubSub.ReceiveMessage(ctx)
...
```
