### ISSUE TITLE
panic on v8.11.5

### ISSUE THREAD

**Issue by go-productive** [redis/go-redis#2484]
The panic stack as follow:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4692e1]

goroutine 16417402349 [running]:
bufio.(*Writer).Write(0xc3b79c89c0, {0x0?, 0x4e58f5?, 0xa9c260?})
        C:/Program Files/Go/src/bufio/bufio.go:680 +0x175
github.com/go-redis/redis/v8/internal/proto.(*Writer).bytes(0xc3b79c8a00, {0x0, 0x42, 0x42})
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/internal/proto/writer.go:124 +0x7c
github.com/go-redis/redis/v8/internal/proto.(*Writer).string(...)
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/internal/proto/writer.go:132
github.com/go-redis/redis/v8/internal/proto.(*Writer).WriteArg(0xc3b79c8a00, {0x95d540?, 0xc62d1bfab0?})
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/internal/proto/writer.go:66 +0x44f
github.com/go-redis/redis/v8/internal/proto.(*Writer).WriteArgs(0xc3b79c8a00, {0xc71fa9aab0, 0x3, 0xed3880?})
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/internal/proto/writer.go:46 +0xba
github.com/go-redis/redis/v8.writeCmd(0xc6f1525800?, {0xb44f70?, 0xc3e9c3d400?})
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/command.go:59 +0x3f
github.com/go-redis/redis/v8.writeCmds(...)
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/command.go:51
github.com/go-redis/redis/v8.(*ClusterClient)._processPipelineNode.func1.1.1(0xc0815055e8?)
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/cluster.go:1189 +0x71
github.com/go-redis/redis/v8/internal/pool.(*Conn).WithWriter(0xc3b79f4cd0, {0xb431d0?, 0xc71fa9aae0?}, 0x736265572d636553?, 0xc00da57c70)
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/internal/pool/conn.go:84 +0x14b
github.com/go-redis/redis/v8.(*ClusterClient)._processPipelineNode.func1.1({0xb431d0, 0xc71fa9aae0}, 0xc71fa9aae0?)
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/cluster.go:1188 +0xc5
github.com/go-redis/redis/v8.(*baseClient).withConn(0xc000f0e100, {0xb431d0?, 0xc71fa9aae0}, 0xc3e9c40140)
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/redis.go:286 +0x36b
github.com/go-redis/redis/v8.(*ClusterClient)._processPipelineNode.func1({0xb431d0, 0xc71fa9aae0}, {0xc1f35713a0, 0x2, 0x2})
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/cluster.go:1187 +0x105
github.com/go-redis/redis/v8.hooks.processPipeline({{0x0?, 0xc2b29fe198?, 0xb3f300?}}, {0xb431d0?, 0xc71fa9aae0?}, {0xc1f35713a0?, 0xc4f8051a98?, 0xc886f17ac0?}, 0xc4f8051aa8?)
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/redis.go:88 +0x85
github.com/go-redis/redis/v8.(*ClusterClient)._processPipelineNode(0xc3e8b1f748?, {0xb431d0?, 0xc71fa9aae0?}, 0xc3e8b1f768?, {0xc1f35713a0?, 0xc3e9ae2b18?, 0xc3e8b1f768?}, 0x47bbd7?)
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/cluster.go:1186 +0x85
github.com/go-redis/redis/v8.(*ClusterClient)._processPipeline.func1(0x100000000b3f4a0?, {0xc1f35713a0, 0x2, 0x2})
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/cluster.go:1120 +0xc9
created by github.com/go-redis/redis/v8.(*ClusterClient)._processPipeline
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/cluster.go:1117 +0x367
```
It is all, no other infos. Sometimes it occured, so I do not know how to reappear it. I try to read the related source code but I can not find the cause.

**Comment by monkey92t** [comment]
I tried many times and still can't reproduce it, can you reproduce it?

**Comment by go-productive** [comment]
> I tried many times and still can't reproduce it, can you reproduce it?

Thank you. I found why. My code reads and writes the string concurrently. 
```
github.com/go-redis/redis/v8/internal/proto.(*Writer).bytes(0xc3b79c8a00, {0x0, 0x42, 0x42})
        F:/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/internal/proto/writer.go:124 +0x7c
```
The stack shows that the byte slice has zero pointer address but its length is not zero. String assignment is not atomic.
