### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Duanshouze** [redis/go-redis#3002]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Current Behavior
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xbaa29e]

goroutine 144316890 [running]:
github.com/go-redis/redis/v8/internal/pool.(*Conn).WithWriter(0xc016f805a0, {0x1e1f4c8?, 0xc010c98f00?}, 0x7270223a22796765?, 0xc0035ceee0)
/usr/local/app/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/internal/pool/conn.go:76 +0x3e
github.com/go-redis/redis/v8.(*baseClient).pipelineProcessCmds(0xc016f805f0, {0x1e1f4c8, 0xc010c98f00}, 0x64696d227b3a3270?, {0xc01baeb290, 0x1, 0x1})
/usr/local/app/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/redis.go:439 +0x85
github.com/go-redis/redis/v8.(*baseClient)._generalProcessPipeline.func1({0x1e1f4c8?, 0xc010c98f00?}, 0x303a22746e756f43?)
/usr/local/app/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/redis.go:426 +0x3d
github.com/go-redis/redis/v8.(*baseClient).withConn.func2()
/usr/local/app/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/redis.go:291 +0x36
created by github.com/go-redis/redis/v8.(*baseClient).withConn
/usr/local/app/go/pkg/mod/github.com/go-redis/redis/v8@v8.11.5/redis.go:291 +0x20a
## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description
version: github.com/go-redis/redis/v8 v8.11.5
problem scenario: Nearly two million calls per minute are made to interfaces such as "redis/hgetall" and "redis/set"
![panic_redis_pointer](https://github.com/redis/go-redis/assets/62098266/84a7a60f-b322-4549-9088-a0b9b822142c)

**Comment by Duanshouze** [comment]
When the number of calls to Redis-related interfaces such as 'redis/hgetal' suddenly increases, the above-mentioned exception occurs, accompanied by a sudden increase in disk block device read bandwidth.
![主调接口数量变化](https://github.com/redis/go-redis/assets/62098266/c8047b4d-0973-4f87-b835-a5829c7517a1)
![磁盘块设备读取带宽](https://github.com/redis/go-redis/assets/62098266/60919460-49b4-4ddc-a773-7926279e7bce)

**Comment by ndyakov** [comment]
@Duanshouze is this still present with v9 ?

**Comment by ndyakov** [comment]
closing for inactivity
